[workspace]
members = ["mysql-protocol", "sql-parser", "mysql-proxy", "config"]

[package]
authors = ["Paul LaCrosse <paul.lacrosse@gmail.com>"]
publish = false
name = "babel"
version = "0.0.3"

[dependencies]
argparse = "0.2.1"
log = "0.3.6"
log4rs = { version = "0.4.8", features = ["toml"] }
mysql-protocol = { path = "mysql-protocol", version = "*"}
sql-parser = { path = "sql-parser", version = "*"}
config = { path = "config", version = "*"}
lazy_static = "0.2.1"
rust-crypto = "0.2.36"
chrono = { version = "0.2.22" }
