[package]
authors = ["Paul LaCrosse <paul.lacrosse@gmail.com>"]
publish = false
name = "agildata-zero"
version = "0.0.5"

[dependencies]
rust-crypto = "0.2.36"
byteorder = "0.5.3"
RustyXML = "0.1.1"
bytes = "0.2.10"
mio = "0.4.4"
log = "0.3"
futures = { git = "https://github.com/alexcrichton/futures-rs" }
futures-cpupool = { git = "https://github.com/alexcrichton/futures-rs" }
env_logger = "0.3"
