[package]
authors = ["Paul LaCrosse <paul.lacrosse@gmail.com>"]
publish = false
name = "babel"
version = "0.0.3"

[dependencies]
parking_lot = "0.2.7"
regex = "0.1.73"
notify = "2.6.3"
lazy_static = "0.2.1"
rust-crypto = "0.2.36"
chrono = { version = "0.2.22" }
byteorder = "*"
RustyXML = "0.1.1"
bytes = "0.2.10"
mio = "0.4.4"
