
refresh_rate = "5 seconds"

[appenders.console]
kind = "console"

[appenders.console.encoder]
pattern = "{d(%+)(local)} [{t}] {h({l})} {M}:{m}{n}"

[[appenders.console.filter]]
kind = "threshold"
level = "debug"

[appenders.file]
kind = "file"
path = "error.log"
pattern = "{d} [{t}] {l} {M}:{m}{n}"

[root]
level = "debug"
appenders = ["console"]

[loggers."test::a"]
level = "info"
appenders = ["file"]
additive = true

[loggers."agildata_zero::proxy::server"]
level = "debug"

