[package]
name = "encrypt"
version = "0.1.0"
authors = ["Andy Grove <andygrove73@gmail.com>"]

[dependencies]
log = "0.3.6"
log4rs = { version = "0.4.8", features = ["toml"] }
lazy_static = "0.2.1"
rust-crypto = "0.2.36"
chrono = { version = "0.2.22" }
parking_lot = "0.2.7"
byteorder = "*"
