[package]
name = "mysql-proxy"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[dependencies]
bytes = "0.2.10"
mio = "0.4.4"
byteorder = "*"
sql-parser = { path = "../sql-parser", version="*" }
